# Based on
#
# docker run --rm --name backend-postgres -e POSTGRES_PASSWORD=docker -p 5433:5432 \
# -v $(pwd)/database:/var/lib/postgresql/data postgres
version: '3'
services:
  database:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - ../database:/var/lib/postgresql/data
    ports:
      - 5433:5432

  backend:
    build: .
    image: news/backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: docker
    ports:
      # local:container
      - 8080:8080
