# Postgres configuration
# TODO ML Think about showing flyway etc.?

server:
  port: ${PORT:8080}

logging:
  level:
    ROOT: WARN
    com.mlesniak: INFO

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # See https://github.com/pgjdbc/pgjdbc/issues/1102 for an explanation
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  datasource:
  # If you do not set these values, these are apparently missing. Spring provides a way to add these values in
  # environment variables, e.g. spring.datasource.url is mapped to SPRING_DATASOURCE_URL etc.
  #
  # We follow this approach to prepare our application to work in containerized and cloud environments where
  # external configuration is often passed using environment variables.
  #
  # url: jdbc:postgresql://localhost:5433/postgres
  # username: postgres
  # password: docker
