# Postgres configuration
# TODO ML Think about showing flyway etc.?

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # See https://github.com/pgjdbc/pgjdbc/issues/1102 for an explanation
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  datasource:
    # TODO ML Use environment variables
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: docker
